fileID = fopen(strcat(strcat('statistical_performance_', init_name) ,'.txt'), 'w');
fprintf(fileID, 'Simulation: %12s \n', init_name);
fprintf(fileID, 'Ocurred: %12s \n', datestr(clock, 0));
fprintf(fileID, 'initial_training_empirical_risk: %6.2f \n', initial_training_empirical_risk);
fprintf(fileID, 'final_training_empirical_risk: %6.2f \n', final_training_empirical_risk);
fprintf(fileID, 'initial_test_empirical_risk: %6.2f \n', initial_test_empirical_risk);
fprintf(fileID, 'final_test_empirical_risk: %6.2f \n', final_test_empirical_risk);
fprintf(fileID, '----- \n');
fprintf(fileID, 'iterations %6.2f \n', iterations );
fprintf(fileID, 'elapsed_time %6.2f \n', elapsed_time );
fprintf(fileID, 'N_size_training_data: %12s', N_size_training_data);
fprintf(fileID, 'N_size_test_data %12s', N_size_test_data);
fclose(fileID);